### ISSUE TITLE
Create a tooltip at the login that says something like "get a login by signing up with any of the participating orgs"!

### ISSUE THREAD

**Issue by threeqube** [bdgio/msol-badger#66]
Afraid lots of folks will instinctually try to login or sign up. Some signal and direction to the user attempting to sign up or login I think would be very useful.

**Comment by threeqube** [comment]
> How's this instead: "Don't have an account? Sign up with any of the participating organizations [link to explore] to get started."

I like it. :+1: Thank you!

**Comment by threeqube** [comment]
Looks great!

![screen shot 2015-06-18 at 10 50 09 am](https://cloud.githubusercontent.com/assets/1424627/8234079/deb6beda-15a7-11e5-89c4-1b4fa953a6f5.png)

nit: It isn't obvious that "participating organization" is hyperlinked. Any chance we can make that a bit more obvious?

**Comment by kayaelle** [comment]
I kind of feel that none of the links on the site are very obvious. Want that I underline them all? Or change the color?

**Comment by threeqube** [comment]
How about a color change? I think blue would work fine. The same color as the blue on the about page I think for consistency.

**Comment by threeqube** [comment]
We netted out on a dark blue. Thanks @kayaelle! :star2:

**Comment by threeqube** [comment]
Looks much better. 

![screen shot 2015-06-18 at 10 50 09 am](https://cloud.githubusercontent.com/assets/1424627/8240156/a808f50c-15ce-11e5-9a1f-9c5ab2690c30.png)

**Comment by threeqube** [comment]
Links look more clickable in prod. :+1: 

![screen shot 2015-06-19 at 8 20 40 am](https://cloud.githubusercontent.com/assets/1424627/8253258/1dfb6dfc-165c-11e5-925b-1cf6c1e00689.png)
