### ISSUE TITLE
Icons and logo rendering issues on Safari

### ISSUE THREAD

**Issue by megcolek** [bdgio/msol-badger#68]
Graphics and logos are messed up on msol.org on safari. 
![screen shot 2015-06-14 at 8 11 32 pm](https://cloud.githubusercontent.com/assets/4603856/8151391/38b775f8-12da-11e5-9598-7a33839ef781.png)
![screen shot 2015-06-14 at 8 11 19 pm](https://cloud.githubusercontent.com/assets/4603856/8151392/3a638964-12da-11e5-831f-c0a8aca1af88.png)

**Comment by threeqube** [comment]
Seems to render fine in safari now. :+1: 

![screen shot 2015-06-19 at 10 19 45 am](https://cloud.githubusercontent.com/assets/1424627/8255274/c27916c6-166c-11e5-8051-1b6cbbb48750.png)
