### ISSUE TITLE
Earn Page: Can the badges be bigger?

### ISSUE THREAD

**Issue by megcolek** [bdgio/msol-badger#71]
Hey there - On this page - https://mainestateoflearning.org/earn - the badges are so small that I can't really see the info on them. Is there a way to make them bigger and use up the space more? There has been so much work put into making them look great, I would love to be able to show them off a little more. Let me know!

Thanks,
M

**Comment by threeqube** [comment]
Looks great in prod! :tada: 

![screen shot 2015-06-19 at 10 20 48 am](https://cloud.githubusercontent.com/assets/1424627/8255292/e4a7894e-166c-11e5-9822-68d8b91e33a0.png)
