### ISSUE TITLE
New Badge like Org logos on Explore page are rendering wonky on mobile

### ISSUE THREAD

**Issue by threeqube** [bdgio/msol-badger#86]
The designs are overlapping each other when rendered at mobile size. 

![screen shot 2015-06-19 at 10 19 05 am](https://cloud.githubusercontent.com/assets/1424627/8255320/2512b7a6-166d-11e5-9f46-2a3df752303a.png)

**Comment by kayaelle** [comment]
hmmm... I don't see this on my phone or in my emulator. How are you viewing this? Can you provide ios & browser?

**Comment by threeqube** [comment]
I just shrank my desktop browser window. You're right. Working fine on my mobile as well. Disregard please!
